// automatic generated by vnlib
static _vn_ns::lex::LR_Terminal g_keywordInfo[] = {
    {"array", 1},
    {"bool", 2},
    {"f32", 3},
    {"f64", 4},
    {"int", 5},
    {"packet", 6},
    {"request", 7},
    {"response", 8},
    {"s16", 9},
    {"s32", 10},
    {"s64", 11},
    {"s8", 12},
    {"string", 13},
    {"struct", 14},
    {"u16", 15},
    {"u32", 16},
    {"u64", 17},
    {"u8", 18},
    {"uint", 19},
    {"vector", 20},
    {(const char *)0, 0}
};

static _vn_ns::lex::LR_Terminal g_symbolInfo[] = {
    {",", 1},
    {";", 2},
    {"<", 3},
    {">", 4},
    {"{", 5},
    {"}", 6},
    {(const char *)0, 0}
};

static _vn_ns::lex::LR_Jump g_state0_jumps[] = {
    _vn_ns::lex::LR_Jump(6, 1),
    _vn_ns::lex::LR_Jump(2, 2),
    _vn_ns::lex::LR_Jump(8, 3),
    _vn_ns::lex::LR_Jump(4, 4),
    _vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 10, 14, 5),
    _vn_ns::lex::LR_Jump(5, 6),
    _vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 10, 6, 7),
    _vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 10, 7, 8),
    _vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 10, 8, 9),
    _vn_ns::lex::LR_Jump()
};

static _vn_ns::lex::LR_Jump g_state1_jumps[] = {
    _vn_ns::lex::LR_Jump(2, 10),
    _vn_ns::lex::LR_Jump(8, 3),
    _vn_ns::lex::LR_Jump(4, 4),
    _vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 10, 14, 5),
    _vn_ns::lex::LR_Jump(5, 6),
    _vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 10, 6, 7),
    _vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 10, 7, 8),
    _vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 10, 8, 9),
    _vn_ns::lex::LR_Jump()
};

static _vn_ns::lex::LR_Reduction g_state1_reduction = {
    1, 0, 0
};

static _vn_ns::lex::LR_Jump g_state2_jumps[] = {
    _vn_ns::lex::LR_Jump()
};

static _vn_ns::lex::LR_Reduction g_state2_reduction = {
    1, 40, 6
};

static _vn_ns::lex::LR_Jump g_state3_jumps[] = {
    _vn_ns::lex::LR_Jump()
};

static _vn_ns::lex::LR_Reduction g_state3_reduction = {
    1, 38, 2
};

static _vn_ns::lex::LR_Jump g_state4_jumps[] = {
    _vn_ns::lex::LR_Jump()
};

static _vn_ns::lex::LR_Reduction g_state4_reduction = {
    1, 39, 2
};

static _vn_ns::lex::LR_Jump g_state5_jumps[] = {
    _vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kToken, 1, 0, 11),
    _vn_ns::lex::LR_Jump()
};

static _vn_ns::lex::LR_Jump g_state6_jumps[] = {
    _vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 2, 3, 12),
    _vn_ns::lex::LR_Jump()
};

static _vn_ns::lex::LR_Jump g_state7_jumps[] = {
    _vn_ns::lex::LR_Jump()
};

static _vn_ns::lex::LR_Reduction g_state7_reduction = {
    1, 29, 5
};

static _vn_ns::lex::LR_Jump g_state8_jumps[] = {
    _vn_ns::lex::LR_Jump()
};

static _vn_ns::lex::LR_Reduction g_state8_reduction = {
    1, 30, 5
};

static _vn_ns::lex::LR_Jump g_state9_jumps[] = {
    _vn_ns::lex::LR_Jump()
};

static _vn_ns::lex::LR_Reduction g_state9_reduction = {
    1, 31, 5
};

static _vn_ns::lex::LR_Jump g_state10_jumps[] = {
    _vn_ns::lex::LR_Jump()
};

static _vn_ns::lex::LR_Reduction g_state10_reduction = {
    2, 41, 6
};

static _vn_ns::lex::LR_Jump g_state11_jumps[] = {
    _vn_ns::lex::LR_Jump(7, 13),
    _vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 2, 5, 14),
    _vn_ns::lex::LR_Jump()
};

static _vn_ns::lex::LR_Jump g_state12_jumps[] = {
    _vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kToken, 5, 0, 15),
    _vn_ns::lex::LR_Jump()
};

static _vn_ns::lex::LR_Jump g_state13_jumps[] = {
    _vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 2, 2, 16),
    _vn_ns::lex::LR_Jump()
};

static _vn_ns::lex::LR_Reduction g_state13_reduction = {
    3, 27, 8
};

static _vn_ns::lex::LR_Jump g_state14_jumps[] = {
    _vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 2, 6, 17),
    _vn_ns::lex::LR_Jump(10, 18),
    _vn_ns::lex::LR_Jump(9, 19),
    _vn_ns::lex::LR_Jump(11, 20),
    _vn_ns::lex::LR_Jump(1, 21),
    _vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 10, 20, 22),
    _vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 10, 1, 23),
    _vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 10, 2, 24),
    _vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 10, 12, 25),
    _vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 10, 18, 26),
    _vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 10, 9, 27),
    _vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 10, 15, 28),
    _vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 10, 10, 29),
    _vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 10, 16, 30),
    _vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 10, 11, 31),
    _vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 10, 17, 32),
    _vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 10, 3, 33),
    _vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 10, 4, 34),
    _vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 10, 5, 35),
    _vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 10, 19, 36),
    _vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 10, 13, 37),
    _vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kToken, 1, 0, 38),
    _vn_ns::lex::LR_Jump()
};

static _vn_ns::lex::LR_Jump g_state15_jumps[] = {
    _vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 2, 4, 39),
    _vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 2, 1, 40),
    _vn_ns::lex::LR_Jump()
};

static _vn_ns::lex::LR_Jump g_state16_jumps[] = {
    _vn_ns::lex::LR_Jump()
};

static _vn_ns::lex::LR_Reduction g_state16_reduction = {
    4, 28, 8
};

static _vn_ns::lex::LR_Jump g_state17_jumps[] = {
    _vn_ns::lex::LR_Jump()
};

static _vn_ns::lex::LR_Reduction g_state17_reduction = {
    2, 25, 7
};

static _vn_ns::lex::LR_Jump g_state18_jumps[] = {
    _vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 2, 6, 41),
    _vn_ns::lex::LR_Jump(9, 42),
    _vn_ns::lex::LR_Jump(11, 20),
    _vn_ns::lex::LR_Jump(1, 21),
    _vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 10, 20, 22),
    _vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 10, 1, 23),
    _vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 10, 2, 24),
    _vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 10, 12, 25),
    _vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 10, 18, 26),
    _vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 10, 9, 27),
    _vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 10, 15, 28),
    _vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 10, 10, 29),
    _vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 10, 16, 30),
    _vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 10, 11, 31),
    _vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 10, 17, 32),
    _vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 10, 3, 33),
    _vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 10, 4, 34),
    _vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 10, 5, 35),
    _vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 10, 19, 36),
    _vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 10, 13, 37),
    _vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kToken, 1, 0, 38),
    _vn_ns::lex::LR_Jump()
};

static _vn_ns::lex::LR_Jump g_state19_jumps[] = {
    _vn_ns::lex::LR_Jump()
};

static _vn_ns::lex::LR_Reduction g_state19_reduction = {
    1, 23, 10
};

static _vn_ns::lex::LR_Jump g_state20_jumps[] = {
    _vn_ns::lex::LR_Jump(3, 43),
    _vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kToken, 1, 0, 44),
    _vn_ns::lex::LR_Jump()
};

static _vn_ns::lex::LR_Jump g_state21_jumps[] = {
    _vn_ns::lex::LR_Jump()
};

static _vn_ns::lex::LR_Reduction g_state21_reduction = {
    1, 16, 11
};

static _vn_ns::lex::LR_Jump g_state22_jumps[] = {
    _vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 2, 3, 45),
    _vn_ns::lex::LR_Jump()
};

static _vn_ns::lex::LR_Jump g_state23_jumps[] = {
    _vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 2, 3, 46),
    _vn_ns::lex::LR_Jump()
};

static _vn_ns::lex::LR_Jump g_state24_jumps[] = {
    _vn_ns::lex::LR_Jump()
};

static _vn_ns::lex::LR_Reduction g_state24_reduction = {
    1, 1, 1
};

static _vn_ns::lex::LR_Jump g_state25_jumps[] = {
    _vn_ns::lex::LR_Jump()
};

static _vn_ns::lex::LR_Reduction g_state25_reduction = {
    1, 2, 1
};

static _vn_ns::lex::LR_Jump g_state26_jumps[] = {
    _vn_ns::lex::LR_Jump()
};

static _vn_ns::lex::LR_Reduction g_state26_reduction = {
    1, 3, 1
};

static _vn_ns::lex::LR_Jump g_state27_jumps[] = {
    _vn_ns::lex::LR_Jump()
};

static _vn_ns::lex::LR_Reduction g_state27_reduction = {
    1, 4, 1
};

static _vn_ns::lex::LR_Jump g_state28_jumps[] = {
    _vn_ns::lex::LR_Jump()
};

static _vn_ns::lex::LR_Reduction g_state28_reduction = {
    1, 5, 1
};

static _vn_ns::lex::LR_Jump g_state29_jumps[] = {
    _vn_ns::lex::LR_Jump()
};

static _vn_ns::lex::LR_Reduction g_state29_reduction = {
    1, 6, 1
};

static _vn_ns::lex::LR_Jump g_state30_jumps[] = {
    _vn_ns::lex::LR_Jump()
};

static _vn_ns::lex::LR_Reduction g_state30_reduction = {
    1, 7, 1
};

static _vn_ns::lex::LR_Jump g_state31_jumps[] = {
    _vn_ns::lex::LR_Jump()
};

static _vn_ns::lex::LR_Reduction g_state31_reduction = {
    1, 8, 1
};

static _vn_ns::lex::LR_Jump g_state32_jumps[] = {
    _vn_ns::lex::LR_Jump()
};

static _vn_ns::lex::LR_Reduction g_state32_reduction = {
    1, 9, 1
};

static _vn_ns::lex::LR_Jump g_state33_jumps[] = {
    _vn_ns::lex::LR_Jump()
};

static _vn_ns::lex::LR_Reduction g_state33_reduction = {
    1, 10, 1
};

static _vn_ns::lex::LR_Jump g_state34_jumps[] = {
    _vn_ns::lex::LR_Jump()
};

static _vn_ns::lex::LR_Reduction g_state34_reduction = {
    1, 11, 1
};

static _vn_ns::lex::LR_Jump g_state35_jumps[] = {
    _vn_ns::lex::LR_Jump()
};

static _vn_ns::lex::LR_Reduction g_state35_reduction = {
    1, 12, 1
};

static _vn_ns::lex::LR_Jump g_state36_jumps[] = {
    _vn_ns::lex::LR_Jump()
};

static _vn_ns::lex::LR_Reduction g_state36_reduction = {
    1, 13, 1
};

static _vn_ns::lex::LR_Jump g_state37_jumps[] = {
    _vn_ns::lex::LR_Jump()
};

static _vn_ns::lex::LR_Reduction g_state37_reduction = {
    1, 14, 1
};

static _vn_ns::lex::LR_Jump g_state38_jumps[] = {
    _vn_ns::lex::LR_Jump()
};

static _vn_ns::lex::LR_Reduction g_state38_reduction = {
    1, 15, 1
};

static _vn_ns::lex::LR_Jump g_state39_jumps[] = {
    _vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kToken, 1, 0, 47),
    _vn_ns::lex::LR_Jump(7, 48),
    _vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 2, 5, 14),
    _vn_ns::lex::LR_Jump()
};

static _vn_ns::lex::LR_Jump g_state40_jumps[] = {
    _vn_ns::lex::LR_Jump(11, 49),
    _vn_ns::lex::LR_Jump(1, 21),
    _vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 10, 20, 22),
    _vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 10, 1, 23),
    _vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 10, 2, 24),
    _vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 10, 12, 25),
    _vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 10, 18, 26),
    _vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 10, 9, 27),
    _vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 10, 15, 28),
    _vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 10, 10, 29),
    _vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 10, 16, 30),
    _vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 10, 11, 31),
    _vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 10, 17, 32),
    _vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 10, 3, 33),
    _vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 10, 4, 34),
    _vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 10, 5, 35),
    _vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 10, 19, 36),
    _vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 10, 13, 37),
    _vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kToken, 1, 0, 38),
    _vn_ns::lex::LR_Jump()
};

static _vn_ns::lex::LR_Jump g_state41_jumps[] = {
    _vn_ns::lex::LR_Jump()
};

static _vn_ns::lex::LR_Reduction g_state41_reduction = {
    3, 26, 7
};

static _vn_ns::lex::LR_Jump g_state42_jumps[] = {
    _vn_ns::lex::LR_Jump()
};

static _vn_ns::lex::LR_Reduction g_state42_reduction = {
    2, 24, 10
};

static _vn_ns::lex::LR_Jump g_state43_jumps[] = {
    _vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 2, 2, 50),
    _vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 2, 1, 51),
    _vn_ns::lex::LR_Jump()
};

static _vn_ns::lex::LR_Reduction g_state43_reduction = {
    2, 21, 9
};

static _vn_ns::lex::LR_Jump g_state44_jumps[] = {
    _vn_ns::lex::LR_Jump()
};

static _vn_ns::lex::LR_Reduction g_state44_reduction = {
    1, 19, 3
};

static _vn_ns::lex::LR_Jump g_state45_jumps[] = {
    _vn_ns::lex::LR_Jump(1, 52),
    _vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 10, 2, 24),
    _vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 10, 12, 25),
    _vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 10, 18, 26),
    _vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 10, 9, 27),
    _vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 10, 15, 28),
    _vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 10, 10, 29),
    _vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 10, 16, 30),
    _vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 10, 11, 31),
    _vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 10, 17, 32),
    _vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 10, 3, 33),
    _vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 10, 4, 34),
    _vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 10, 5, 35),
    _vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 10, 19, 36),
    _vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 10, 13, 37),
    _vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kToken, 1, 0, 38),
    _vn_ns::lex::LR_Jump()
};

static _vn_ns::lex::LR_Jump g_state46_jumps[] = {
    _vn_ns::lex::LR_Jump(1, 53),
    _vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 10, 2, 24),
    _vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 10, 12, 25),
    _vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 10, 18, 26),
    _vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 10, 9, 27),
    _vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 10, 15, 28),
    _vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 10, 10, 29),
    _vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 10, 16, 30),
    _vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 10, 11, 31),
    _vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 10, 17, 32),
    _vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 10, 3, 33),
    _vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 10, 4, 34),
    _vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 10, 5, 35),
    _vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 10, 19, 36),
    _vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 10, 13, 37),
    _vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kToken, 1, 0, 38),
    _vn_ns::lex::LR_Jump()
};

static _vn_ns::lex::LR_Jump g_state47_jumps[] = {
    _vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 2, 2, 54),
    _vn_ns::lex::LR_Jump()
};

static _vn_ns::lex::LR_Reduction g_state47_reduction = {
    5, 32, 4
};

static _vn_ns::lex::LR_Jump g_state48_jumps[] = {
    _vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kToken, 1, 0, 55),
    _vn_ns::lex::LR_Jump()
};

static _vn_ns::lex::LR_Jump g_state49_jumps[] = {
    _vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 2, 4, 56),
    _vn_ns::lex::LR_Jump()
};

static _vn_ns::lex::LR_Jump g_state50_jumps[] = {
    _vn_ns::lex::LR_Jump()
};

static _vn_ns::lex::LR_Reduction g_state50_reduction = {
    3, 22, 9
};

static _vn_ns::lex::LR_Jump g_state51_jumps[] = {
    _vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kToken, 1, 0, 57),
    _vn_ns::lex::LR_Jump()
};

static _vn_ns::lex::LR_Jump g_state52_jumps[] = {
    _vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 2, 4, 58),
    _vn_ns::lex::LR_Jump()
};

static _vn_ns::lex::LR_Jump g_state53_jumps[] = {
    _vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 2, 1, 59),
    _vn_ns::lex::LR_Jump()
};

static _vn_ns::lex::LR_Jump g_state54_jumps[] = {
    _vn_ns::lex::LR_Jump()
};

static _vn_ns::lex::LR_Reduction g_state54_reduction = {
    6, 33, 4
};

static _vn_ns::lex::LR_Jump g_state55_jumps[] = {
    _vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 2, 2, 60),
    _vn_ns::lex::LR_Jump()
};

static _vn_ns::lex::LR_Reduction g_state55_reduction = {
    6, 34, 4
};

static _vn_ns::lex::LR_Jump g_state56_jumps[] = {
    _vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kToken, 1, 0, 61),
    _vn_ns::lex::LR_Jump()
};

static _vn_ns::lex::LR_Jump g_state57_jumps[] = {
    _vn_ns::lex::LR_Jump()
};

static _vn_ns::lex::LR_Reduction g_state57_reduction = {
    3, 20, 3
};

static _vn_ns::lex::LR_Jump g_state58_jumps[] = {
    _vn_ns::lex::LR_Jump()
};

static _vn_ns::lex::LR_Reduction g_state58_reduction = {
    4, 17, 11
};

static _vn_ns::lex::LR_Jump g_state59_jumps[] = {
    _vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kToken, 5, 0, 62),
    _vn_ns::lex::LR_Jump()
};

static _vn_ns::lex::LR_Jump g_state60_jumps[] = {
    _vn_ns::lex::LR_Jump()
};

static _vn_ns::lex::LR_Reduction g_state60_reduction = {
    7, 35, 4
};

static _vn_ns::lex::LR_Jump g_state61_jumps[] = {
    _vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 2, 2, 63),
    _vn_ns::lex::LR_Jump()
};

static _vn_ns::lex::LR_Reduction g_state61_reduction = {
    7, 36, 4
};

static _vn_ns::lex::LR_Jump g_state62_jumps[] = {
    _vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 2, 4, 64),
    _vn_ns::lex::LR_Jump()
};

static _vn_ns::lex::LR_Jump g_state63_jumps[] = {
    _vn_ns::lex::LR_Jump()
};

static _vn_ns::lex::LR_Reduction g_state63_reduction = {
    8, 37, 4
};

static _vn_ns::lex::LR_Jump g_state64_jumps[] = {
    _vn_ns::lex::LR_Jump()
};

static _vn_ns::lex::LR_Reduction g_state64_reduction = {
    6, 18, 11
};

static _vn_ns::lex::LR_State g_states[] = {
    {0, g_state0_jumps, (_vn_ns::lex::LR_Reduction *)0},
    {1, g_state1_jumps, &g_state1_reduction},
    {2, g_state2_jumps, &g_state2_reduction},
    {3, g_state3_jumps, &g_state3_reduction},
    {4, g_state4_jumps, &g_state4_reduction},
    {5, g_state5_jumps, (_vn_ns::lex::LR_Reduction *)0},
    {6, g_state6_jumps, (_vn_ns::lex::LR_Reduction *)0},
    {7, g_state7_jumps, &g_state7_reduction},
    {8, g_state8_jumps, &g_state8_reduction},
    {9, g_state9_jumps, &g_state9_reduction},
    {10, g_state10_jumps, &g_state10_reduction},
    {11, g_state11_jumps, (_vn_ns::lex::LR_Reduction *)0},
    {12, g_state12_jumps, (_vn_ns::lex::LR_Reduction *)0},
    {13, g_state13_jumps, &g_state13_reduction},
    {14, g_state14_jumps, (_vn_ns::lex::LR_Reduction *)0},
    {15, g_state15_jumps, (_vn_ns::lex::LR_Reduction *)0},
    {16, g_state16_jumps, &g_state16_reduction},
    {17, g_state17_jumps, &g_state17_reduction},
    {18, g_state18_jumps, (_vn_ns::lex::LR_Reduction *)0},
    {19, g_state19_jumps, &g_state19_reduction},
    {20, g_state20_jumps, (_vn_ns::lex::LR_Reduction *)0},
    {21, g_state21_jumps, &g_state21_reduction},
    {22, g_state22_jumps, (_vn_ns::lex::LR_Reduction *)0},
    {23, g_state23_jumps, (_vn_ns::lex::LR_Reduction *)0},
    {24, g_state24_jumps, &g_state24_reduction},
    {25, g_state25_jumps, &g_state25_reduction},
    {26, g_state26_jumps, &g_state26_reduction},
    {27, g_state27_jumps, &g_state27_reduction},
    {28, g_state28_jumps, &g_state28_reduction},
    {29, g_state29_jumps, &g_state29_reduction},
    {30, g_state30_jumps, &g_state30_reduction},
    {31, g_state31_jumps, &g_state31_reduction},
    {32, g_state32_jumps, &g_state32_reduction},
    {33, g_state33_jumps, &g_state33_reduction},
    {34, g_state34_jumps, &g_state34_reduction},
    {35, g_state35_jumps, &g_state35_reduction},
    {36, g_state36_jumps, &g_state36_reduction},
    {37, g_state37_jumps, &g_state37_reduction},
    {38, g_state38_jumps, &g_state38_reduction},
    {39, g_state39_jumps, (_vn_ns::lex::LR_Reduction *)0},
    {40, g_state40_jumps, (_vn_ns::lex::LR_Reduction *)0},
    {41, g_state41_jumps, &g_state41_reduction},
    {42, g_state42_jumps, &g_state42_reduction},
    {43, g_state43_jumps, &g_state43_reduction},
    {44, g_state44_jumps, &g_state44_reduction},
    {45, g_state45_jumps, (_vn_ns::lex::LR_Reduction *)0},
    {46, g_state46_jumps, (_vn_ns::lex::LR_Reduction *)0},
    {47, g_state47_jumps, &g_state47_reduction},
    {48, g_state48_jumps, (_vn_ns::lex::LR_Reduction *)0},
    {49, g_state49_jumps, (_vn_ns::lex::LR_Reduction *)0},
    {50, g_state50_jumps, &g_state50_reduction},
    {51, g_state51_jumps, (_vn_ns::lex::LR_Reduction *)0},
    {52, g_state52_jumps, (_vn_ns::lex::LR_Reduction *)0},
    {53, g_state53_jumps, (_vn_ns::lex::LR_Reduction *)0},
    {54, g_state54_jumps, &g_state54_reduction},
    {55, g_state55_jumps, &g_state55_reduction},
    {56, g_state56_jumps, (_vn_ns::lex::LR_Reduction *)0},
    {57, g_state57_jumps, &g_state57_reduction},
    {58, g_state58_jumps, &g_state58_reduction},
    {59, g_state59_jumps, (_vn_ns::lex::LR_Reduction *)0},
    {60, g_state60_jumps, &g_state60_reduction},
    {61, g_state61_jumps, &g_state61_reduction},
    {62, g_state62_jumps, (_vn_ns::lex::LR_Reduction *)0},
    {63, g_state63_jumps, &g_state63_reduction},
    {64, g_state64_jumps, &g_state64_reduction},
    {0xFFFFFFFF, (_vn_ns::lex::LR_Jump *)0, (_vn_ns::lex::LR_Reduction *)0}
};
