// automatic generated by vnlib.
enum {
    PROD__0 = 0, // -> script
    PROD_array_0 = 19, //array -> '[' ']'
    PROD_array_1 = 20, //array -> '[' value_list ']'
    PROD_item_0 = 16, //item -> @string_literal ':' value
    PROD_item_list_0 = 17, //item_list -> item
    PROD_item_list_1 = 18, //item_list -> item_list ',' item
    PROD_number_0 = 1, //number -> @integer
    PROD_number_1 = 2, //number -> @long_integer
    PROD_number_2 = 3, //number -> @float
    PROD_number_3 = 4, //number -> @double
    PROD_object_0 = 21, //object -> '{' '}'
    PROD_object_1 = 22, //object -> '{' item_list '}'
    PROD_script_0 = 23, //script -> object
    PROD_value_0 = 5, //value -> 'null'
    PROD_value_1 = 6, //value -> 'true'
    PROD_value_2 = 7, //value -> 'false'
    PROD_value_3 = 8, //value -> number
    PROD_value_4 = 9, //value -> '+' number
    PROD_value_5 = 10, //value -> '-' number
    PROD_value_6 = 11, //value -> @string_literal
    PROD_value_7 = 12, //value -> array
    PROD_value_8 = 13, //value -> object
    PROD_value_list_0 = 14, //value_list -> value
    PROD_value_list_1 = 15, //value_list -> value_list ',' value
    PROD_COUNT = 24
};
