// automatic generated by vnlib
static _vn_ns::lex::LR_Terminal g_keywordInfo[] = {
	{"false", 1},
	{"null", 2},
	{"true", 3},
	{(const char *)0, 0}
};

static _vn_ns::lex::LR_Terminal g_symbolInfo[] = {
	{"+", 1},
	{"-", 2},
	{"=", 3},
	{"@", 4},
	{"[", 5},
	{"]", 6},
	{"{", 7},
	{"}", 8},
	{(const char *)0, 0}
};

static _vn_ns::lex::LR_Jump g_state0_jumps[] = {
	_vn_ns::lex::LR_Jump(8, 1),
	_vn_ns::lex::LR_Jump(7, 2),
	_vn_ns::lex::LR_Jump(6, 3),
	_vn_ns::lex::LR_Jump(9, 4),
	_vn_ns::lex::LR_Jump(1, 5),
	_vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 10, 2, 6),
	_vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 10, 3, 7),
	_vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 10, 1, 8),
	_vn_ns::lex::LR_Jump(2, 9),
	_vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 2, 1, 10),
	_vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 2, 2, 11),
	_vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kToken, 9, 0, 12),
	_vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kToken, 1, 0, 13),
	_vn_ns::lex::LR_Jump(3, 14),
	_vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kToken, 5, 0, 15),
	_vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kToken, 6, 0, 16),
	_vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kToken, 7, 0, 17),
	_vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kToken, 8, 0, 18),
	_vn_ns::lex::LR_Jump(5, 19),
	_vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 2, 5, 20),
	_vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 2, 4, 21),
	_vn_ns::lex::LR_Jump()
};

static _vn_ns::lex::LR_Jump g_state1_jumps[] = {
	_vn_ns::lex::LR_Jump()
};

static _vn_ns::lex::LR_Reduction g_state1_reduction = {
	1, 0, 0
};

static _vn_ns::lex::LR_Jump g_state2_jumps[] = {
	_vn_ns::lex::LR_Jump(6, 22),
	_vn_ns::lex::LR_Jump(9, 4),
	_vn_ns::lex::LR_Jump(1, 5),
	_vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 10, 2, 6),
	_vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 10, 3, 7),
	_vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 10, 1, 8),
	_vn_ns::lex::LR_Jump(2, 9),
	_vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 2, 1, 10),
	_vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 2, 2, 11),
	_vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kToken, 9, 0, 12),
	_vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kToken, 1, 0, 13),
	_vn_ns::lex::LR_Jump(3, 14),
	_vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kToken, 5, 0, 15),
	_vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kToken, 6, 0, 16),
	_vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kToken, 7, 0, 17),
	_vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kToken, 8, 0, 18),
	_vn_ns::lex::LR_Jump(5, 19),
	_vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 2, 5, 20),
	_vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 2, 4, 21),
	_vn_ns::lex::LR_Jump()
};

static _vn_ns::lex::LR_Reduction g_state2_reduction = {
	1, 27, 8
};

static _vn_ns::lex::LR_Jump g_state3_jumps[] = {
	_vn_ns::lex::LR_Jump()
};

static _vn_ns::lex::LR_Reduction g_state3_reduction = {
	1, 22, 7
};

static _vn_ns::lex::LR_Jump g_state4_jumps[] = {
	_vn_ns::lex::LR_Jump()
};

static _vn_ns::lex::LR_Reduction g_state4_reduction = {
	1, 24, 6
};

static _vn_ns::lex::LR_Jump g_state5_jumps[] = {
	_vn_ns::lex::LR_Jump()
};

static _vn_ns::lex::LR_Reduction g_state5_reduction = {
	1, 25, 6
};

static _vn_ns::lex::LR_Jump g_state6_jumps[] = {
	_vn_ns::lex::LR_Jump()
};

static _vn_ns::lex::LR_Reduction g_state6_reduction = {
	1, 1, 9
};

static _vn_ns::lex::LR_Jump g_state7_jumps[] = {
	_vn_ns::lex::LR_Jump()
};

static _vn_ns::lex::LR_Reduction g_state7_reduction = {
	1, 2, 9
};

static _vn_ns::lex::LR_Jump g_state8_jumps[] = {
	_vn_ns::lex::LR_Jump()
};

static _vn_ns::lex::LR_Reduction g_state8_reduction = {
	1, 3, 9
};

static _vn_ns::lex::LR_Jump g_state9_jumps[] = {
	_vn_ns::lex::LR_Jump()
};

static _vn_ns::lex::LR_Reduction g_state9_reduction = {
	1, 4, 9
};

static _vn_ns::lex::LR_Jump g_state10_jumps[] = {
	_vn_ns::lex::LR_Jump(2, 23),
	_vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kToken, 5, 0, 15),
	_vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kToken, 6, 0, 16),
	_vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kToken, 7, 0, 17),
	_vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kToken, 8, 0, 18),
	_vn_ns::lex::LR_Jump()
};

static _vn_ns::lex::LR_Jump g_state11_jumps[] = {
	_vn_ns::lex::LR_Jump(2, 24),
	_vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kToken, 5, 0, 15),
	_vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kToken, 6, 0, 16),
	_vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kToken, 7, 0, 17),
	_vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kToken, 8, 0, 18),
	_vn_ns::lex::LR_Jump()
};

static _vn_ns::lex::LR_Jump g_state12_jumps[] = {
	_vn_ns::lex::LR_Jump()
};

static _vn_ns::lex::LR_Reduction g_state12_reduction = {
	1, 7, 9
};

static _vn_ns::lex::LR_Jump g_state13_jumps[] = {
	_vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 2, 3, 25),
	_vn_ns::lex::LR_Jump()
};

static _vn_ns::lex::LR_Reduction g_state13_reduction = {
	1, 8, 9
};

static _vn_ns::lex::LR_Jump g_state14_jumps[] = {
	_vn_ns::lex::LR_Jump()
};

static _vn_ns::lex::LR_Reduction g_state14_reduction = {
	1, 9, 9
};

static _vn_ns::lex::LR_Jump g_state15_jumps[] = {
	_vn_ns::lex::LR_Jump()
};

static _vn_ns::lex::LR_Reduction g_state15_reduction = {
	1, 10, 2
};

static _vn_ns::lex::LR_Jump g_state16_jumps[] = {
	_vn_ns::lex::LR_Jump()
};

static _vn_ns::lex::LR_Reduction g_state16_reduction = {
	1, 11, 2
};

static _vn_ns::lex::LR_Jump g_state17_jumps[] = {
	_vn_ns::lex::LR_Jump()
};

static _vn_ns::lex::LR_Reduction g_state17_reduction = {
	1, 12, 2
};

static _vn_ns::lex::LR_Jump g_state18_jumps[] = {
	_vn_ns::lex::LR_Jump()
};

static _vn_ns::lex::LR_Reduction g_state18_reduction = {
	1, 13, 2
};

static _vn_ns::lex::LR_Jump g_state19_jumps[] = {
	_vn_ns::lex::LR_Jump(4, 26),
	_vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 2, 7, 27),
	_vn_ns::lex::LR_Jump()
};

static _vn_ns::lex::LR_Jump g_state20_jumps[] = {
	_vn_ns::lex::LR_Jump(10, 28),
	_vn_ns::lex::LR_Jump(9, 29),
	_vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 10, 2, 6),
	_vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 10, 3, 7),
	_vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 10, 1, 8),
	_vn_ns::lex::LR_Jump(2, 9),
	_vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 2, 1, 10),
	_vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 2, 2, 11),
	_vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kToken, 9, 0, 12),
	_vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kToken, 1, 0, 30),
	_vn_ns::lex::LR_Jump(3, 14),
	_vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kToken, 5, 0, 15),
	_vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kToken, 6, 0, 16),
	_vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kToken, 7, 0, 17),
	_vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kToken, 8, 0, 18),
	_vn_ns::lex::LR_Jump(5, 19),
	_vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 2, 5, 20),
	_vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 2, 4, 21),
	_vn_ns::lex::LR_Jump()
};

static _vn_ns::lex::LR_Jump g_state21_jumps[] = {
	_vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kToken, 1, 0, 31),
	_vn_ns::lex::LR_Jump()
};

static _vn_ns::lex::LR_Reduction g_state21_reduction = {
	1, 18, 5
};

static _vn_ns::lex::LR_Jump g_state22_jumps[] = {
	_vn_ns::lex::LR_Jump()
};

static _vn_ns::lex::LR_Reduction g_state22_reduction = {
	2, 23, 7
};

static _vn_ns::lex::LR_Jump g_state23_jumps[] = {
	_vn_ns::lex::LR_Jump()
};

static _vn_ns::lex::LR_Reduction g_state23_reduction = {
	2, 5, 9
};

static _vn_ns::lex::LR_Jump g_state24_jumps[] = {
	_vn_ns::lex::LR_Jump()
};

static _vn_ns::lex::LR_Reduction g_state24_reduction = {
	2, 6, 9
};

static _vn_ns::lex::LR_Jump g_state25_jumps[] = {
	_vn_ns::lex::LR_Jump(9, 32),
	_vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 10, 2, 6),
	_vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 10, 3, 7),
	_vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 10, 1, 8),
	_vn_ns::lex::LR_Jump(2, 9),
	_vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 2, 1, 10),
	_vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 2, 2, 11),
	_vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kToken, 9, 0, 12),
	_vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kToken, 1, 0, 30),
	_vn_ns::lex::LR_Jump(3, 14),
	_vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kToken, 5, 0, 15),
	_vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kToken, 6, 0, 16),
	_vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kToken, 7, 0, 17),
	_vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kToken, 8, 0, 18),
	_vn_ns::lex::LR_Jump(5, 19),
	_vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 2, 5, 20),
	_vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 2, 4, 21),
	_vn_ns::lex::LR_Jump()
};

static _vn_ns::lex::LR_Jump g_state26_jumps[] = {
	_vn_ns::lex::LR_Jump()
};

static _vn_ns::lex::LR_Reduction g_state26_reduction = {
	2, 16, 3
};

static _vn_ns::lex::LR_Jump g_state27_jumps[] = {
	_vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 2, 8, 33),
	_vn_ns::lex::LR_Jump(7, 34),
	_vn_ns::lex::LR_Jump(6, 3),
	_vn_ns::lex::LR_Jump(9, 4),
	_vn_ns::lex::LR_Jump(1, 5),
	_vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 10, 2, 6),
	_vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 10, 3, 7),
	_vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 10, 1, 8),
	_vn_ns::lex::LR_Jump(2, 9),
	_vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 2, 1, 10),
	_vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 2, 2, 11),
	_vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kToken, 9, 0, 12),
	_vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kToken, 1, 0, 13),
	_vn_ns::lex::LR_Jump(3, 14),
	_vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kToken, 5, 0, 15),
	_vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kToken, 6, 0, 16),
	_vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kToken, 7, 0, 17),
	_vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kToken, 8, 0, 18),
	_vn_ns::lex::LR_Jump(5, 19),
	_vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 2, 5, 20),
	_vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 2, 4, 21),
	_vn_ns::lex::LR_Jump()
};

static _vn_ns::lex::LR_Jump g_state28_jumps[] = {
	_vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 2, 6, 35),
	_vn_ns::lex::LR_Jump(9, 36),
	_vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 10, 2, 6),
	_vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 10, 3, 7),
	_vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 10, 1, 8),
	_vn_ns::lex::LR_Jump(2, 9),
	_vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 2, 1, 10),
	_vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 2, 2, 11),
	_vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kToken, 9, 0, 12),
	_vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kToken, 1, 0, 30),
	_vn_ns::lex::LR_Jump(3, 14),
	_vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kToken, 5, 0, 15),
	_vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kToken, 6, 0, 16),
	_vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kToken, 7, 0, 17),
	_vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kToken, 8, 0, 18),
	_vn_ns::lex::LR_Jump(5, 19),
	_vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 2, 5, 20),
	_vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 2, 4, 21),
	_vn_ns::lex::LR_Jump()
};

static _vn_ns::lex::LR_Jump g_state29_jumps[] = {
	_vn_ns::lex::LR_Jump()
};

static _vn_ns::lex::LR_Reduction g_state29_reduction = {
	1, 14, 10
};

static _vn_ns::lex::LR_Jump g_state30_jumps[] = {
	_vn_ns::lex::LR_Jump()
};

static _vn_ns::lex::LR_Reduction g_state30_reduction = {
	1, 8, 9
};

static _vn_ns::lex::LR_Jump g_state31_jumps[] = {
	_vn_ns::lex::LR_Jump()
};

static _vn_ns::lex::LR_Reduction g_state31_reduction = {
	2, 19, 5
};

static _vn_ns::lex::LR_Jump g_state32_jumps[] = {
	_vn_ns::lex::LR_Jump()
};

static _vn_ns::lex::LR_Reduction g_state32_reduction = {
	3, 26, 1
};

static _vn_ns::lex::LR_Jump g_state33_jumps[] = {
	_vn_ns::lex::LR_Jump()
};

static _vn_ns::lex::LR_Reduction g_state33_reduction = {
	2, 20, 4
};

static _vn_ns::lex::LR_Jump g_state34_jumps[] = {
	_vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 2, 8, 37),
	_vn_ns::lex::LR_Jump(6, 22),
	_vn_ns::lex::LR_Jump(9, 4),
	_vn_ns::lex::LR_Jump(1, 5),
	_vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 10, 2, 6),
	_vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 10, 3, 7),
	_vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 10, 1, 8),
	_vn_ns::lex::LR_Jump(2, 9),
	_vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 2, 1, 10),
	_vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 2, 2, 11),
	_vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kToken, 9, 0, 12),
	_vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kToken, 1, 0, 13),
	_vn_ns::lex::LR_Jump(3, 14),
	_vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kToken, 5, 0, 15),
	_vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kToken, 6, 0, 16),
	_vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kToken, 7, 0, 17),
	_vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kToken, 8, 0, 18),
	_vn_ns::lex::LR_Jump(5, 19),
	_vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 2, 5, 20),
	_vn_ns::lex::LR_Jump(_vn_ns::lex::LR_Jump::kTokenWithValue, 2, 4, 21),
	_vn_ns::lex::LR_Jump()
};

static _vn_ns::lex::LR_Jump g_state35_jumps[] = {
	_vn_ns::lex::LR_Jump()
};

static _vn_ns::lex::LR_Reduction g_state35_reduction = {
	3, 17, 3
};

static _vn_ns::lex::LR_Jump g_state36_jumps[] = {
	_vn_ns::lex::LR_Jump()
};

static _vn_ns::lex::LR_Reduction g_state36_reduction = {
	2, 15, 10
};

static _vn_ns::lex::LR_Jump g_state37_jumps[] = {
	_vn_ns::lex::LR_Jump()
};

static _vn_ns::lex::LR_Reduction g_state37_reduction = {
	3, 21, 4
};

static _vn_ns::lex::LR_State g_states[] = {
	{0, g_state0_jumps, (_vn_ns::lex::LR_Reduction *)0},
	{1, g_state1_jumps, &g_state1_reduction},
	{2, g_state2_jumps, &g_state2_reduction},
	{3, g_state3_jumps, &g_state3_reduction},
	{4, g_state4_jumps, &g_state4_reduction},
	{5, g_state5_jumps, &g_state5_reduction},
	{6, g_state6_jumps, &g_state6_reduction},
	{7, g_state7_jumps, &g_state7_reduction},
	{8, g_state8_jumps, &g_state8_reduction},
	{9, g_state9_jumps, &g_state9_reduction},
	{10, g_state10_jumps, (_vn_ns::lex::LR_Reduction *)0},
	{11, g_state11_jumps, (_vn_ns::lex::LR_Reduction *)0},
	{12, g_state12_jumps, &g_state12_reduction},
	{13, g_state13_jumps, &g_state13_reduction},
	{14, g_state14_jumps, &g_state14_reduction},
	{15, g_state15_jumps, &g_state15_reduction},
	{16, g_state16_jumps, &g_state16_reduction},
	{17, g_state17_jumps, &g_state17_reduction},
	{18, g_state18_jumps, &g_state18_reduction},
	{19, g_state19_jumps, (_vn_ns::lex::LR_Reduction *)0},
	{20, g_state20_jumps, (_vn_ns::lex::LR_Reduction *)0},
	{21, g_state21_jumps, &g_state21_reduction},
	{22, g_state22_jumps, &g_state22_reduction},
	{23, g_state23_jumps, &g_state23_reduction},
	{24, g_state24_jumps, &g_state24_reduction},
	{25, g_state25_jumps, (_vn_ns::lex::LR_Reduction *)0},
	{26, g_state26_jumps, &g_state26_reduction},
	{27, g_state27_jumps, (_vn_ns::lex::LR_Reduction *)0},
	{28, g_state28_jumps, (_vn_ns::lex::LR_Reduction *)0},
	{29, g_state29_jumps, &g_state29_reduction},
	{30, g_state30_jumps, &g_state30_reduction},
	{31, g_state31_jumps, &g_state31_reduction},
	{32, g_state32_jumps, &g_state32_reduction},
	{33, g_state33_jumps, &g_state33_reduction},
	{34, g_state34_jumps, (_vn_ns::lex::LR_Reduction *)0},
	{35, g_state35_jumps, &g_state35_reduction},
	{36, g_state36_jumps, &g_state36_reduction},
	{37, g_state37_jumps, &g_state37_reduction},
	{0xFFFFFFFF, (_vn_ns::lex::LR_Jump *)0, (_vn_ns::lex::LR_Reduction *)0}
};
